# for dockerized startup
spring:
  data:
    mongodb:
      uri: mongodb://root:toor@mongo:27017/warehouse?authSource=admin

    redis:
      host: redis
      port: 6379
      password: toor
      repositories:
        enabled: false

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
    registry:
      url: http://kafka-schema-registry:8081

redis.ttl: 3

nats:
  url: nats://nats:4222
