# for local startup
spring:
  data:
    mongodb:
      uri: mongodb://root:toor@localhost:27017/warehouse?authSource=admin

    redis:
      host: localhost
      port: 6379
      password: toor
      repositories:
        enabled: false

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
    registry:
      url: http://localhost:8081

redis.ttl: 3

nats:
  url: nats://localhost:4222
