# for local startup
spring:
  data:
    mongodb:
      uri: mongodb://root:toor@localhost:27017/warehouse?authSource=admin

    redis:
      host: localhost
      port: 6379
      password: toor
      repositories:
        enabled: false

nats:
  url: nats://localhost:4222
