version: "3.5"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      nats:
        condition: service_started
      mongo:
        condition: service_healthy
