# for dockerized startup
spring:
  data.mongodb:
    uri: mongodb://root:toor@mongo:27017/warehouse?authSource=admin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/warehouse
    username: root
    password: toor
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
