name: Checks

on:
  push:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start NATS and MongoDB
        run: docker-compose up -d --scale app=0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: '17'

      - name: Run build
        run: ./gradlew build
